<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SAR Technology_toggle</name>
   <tag></tag>
   <elementGuidId>ad13c3cd-0e89-489f-b373-beae6240beb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdf73307-97a6-4341-8c06-fbf04aea6a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle</value>
      <webElementGuid>55c24d8c-ba4a-4190-ab4a-7701a76bd725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;toggle&quot;]</value>
      <webElementGuid>995e8149-0fac-4026-a66c-131578d5eeb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>987a99a9-5fa0-4671-aaea-575d07b314e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
