<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea</name>
   <tag></tag>
   <elementGuidId>6800a877-acb8-4657-ac88-5131fd90a1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c9bb23a4-f581-48f9-a841-a1975d6162bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Message</value>
      <webElementGuid>526eaadf-9b1b-4a61-87bd-c1356f2ab450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[1]/div[@class=&quot;contact&quot;]/div[@class=&quot;contact-form&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;input100&quot;]/textarea[1]</value>
      <webElementGuid>9a0c8709-b2a5-46d4-9658-207d0f2b3b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dd989ebc-39b6-4999-9dc4-1292d7ee3e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Message']</value>
      <webElementGuid>d4aee4db-9190-4f14-a005-9b09c363049a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
